# -*- coding: utf-8 -*-
"""12 Movies Stacked Bar Chart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OJZCqG8FX4IUmjD6itdvTcmHWtUihA0I
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5', 'Movie 6', 'Movie 7', 'Movie 8', 'Movie 9', 'Movie 10', 'Movie 11', 'Movie 12'],
    'Action': [5, 30, 30, 30, 20, 0, 35, 20, 5, 50, 45, 10],
    'Adventure': [0, 40, 20, 30, 20, 25, 25, 30, 30, 35, 15, 40],
    'Romance': [50, 10, 15, 0, 20, 0, 0, 5, 10, 10, 0, 20],
    'Fantasy': [30, 20, 30, 20, 20, 5, 15, 30, 35, 5, 20, 0],
    'Family': [5, 0, 0, 0, 0, 35, 0, 5, 15, 0, 10, 20],
    'Horror': [10, 0, 5, 20, 20, 35, 25, 10, 5, 0, 10, 10]
}

df = pd.DataFrame(data)

# Set 'Movie No.' column as the index
df.set_index('Movie No.', inplace=True)

# Calculate percentage values for each genre within each movie
total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Create a stacked bar chart
plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")

# Use Seaborn's barplot function with stacked=True
ax = df_percentage.plot(kind='bar', stacked=True, cmap='viridis')

# Set the title and labels
plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Movies')
plt.ylabel('Percentage')

# Customize legend
handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5', 'Movie 6', 'Movie 7', 'Movie 8', 'Movie 9', 'Movie 10', 'Movie 11', 'Movie 12'],
    'Action': [5, 30, 30, 30, 20, 0, 35, 20, 5, 50, 45, 10],
    'Adventure': [0, 40, 20, 30, 20, 25, 25, 30, 30, 35, 15, 40],
    'Romance': [50, 10, 15, 0, 20, 0, 0, 5, 10, 10, 0, 20],
    'Fantasy': [30, 20, 30, 20, 20, 5, 15, 30, 35, 5, 20, 0],
    'Family': [5, 0, 0, 0, 0, 35, 0, 5, 15, 0, 10, 20],
    'Horror': [10, 0, 5, 20, 20, 35, 25, 10, 5, 0, 10, 10]
}

df = pd.DataFrame(data)

# Set 'Movie No.' column as the index
df.set_index('Movie No.', inplace=True)

# Calculate percentage values for each genre within each movie
total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Create a stacked bar chart
plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")

# Use Seaborn's barplot function with stacked=True
ax = df_percentage.plot(kind='bar', stacked=True, cmap='YlOrRd')



# Set the title and labels
plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Movies')
plt.ylabel('Percentage')

# Customize legend
handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5', 'Movie 6', 'Movie 7', 'Movie 8', 'Movie 9', 'Movie 10', 'Movie 11', 'Movie 12'],
    'Action': [5, 30, 30, 30, 20, 0, 35, 20, 5, 50, 45, 10],
    'Adventure': [0, 40, 20, 30, 20, 25, 25, 30, 30, 35, 15, 40],
    'Romance': [50, 10, 15, 0, 20, 0, 0, 5, 10, 10, 0, 20],
    'Fantasy': [30, 20, 30, 20, 20, 5, 15, 30, 35, 5, 20, 0],
    'Family': [5, 0, 0, 0, 0, 35, 0, 5, 15, 0, 10, 20],
    'Horror': [10, 0, 5, 20, 20, 35, 25, 10, 5, 0, 10, 10]
}

df = pd.DataFrame(data)

# Set 'Movie No.' column as the index
df.set_index('Movie No.', inplace=True)

# Calculate percentage values for each genre within each movie
total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Create a stacked bar chart with movies on the y-axis and percentages on the x-axis
plt.figure(figsize=(10, 8))
sns.set(style="whitegrid")

# Use Seaborn's barplot function with stacked=True
ax = df_percentage.plot(kind='barh', stacked=True, cmap='viridis')

# Set the title and labels
plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Percentage')
plt.ylabel('Movies')

# Customize legend
handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5', 'Movie 6', 'Movie 7', 'Movie 8', 'Movie 9', 'Movie 10', 'Movie 11', 'Movie 12'],
    'Action': [5, 30, 30, 30, 20, 0, 35, 20, 5, 50, 45, 10],
    'Adventure': [0, 40, 20, 30, 20, 25, 25, 30, 30, 35, 15, 40],
    'Romance': [50, 10, 15, 0, 20, 0, 0, 5, 10, 10, 0, 20],
    'Fantasy': [30, 20, 30, 20, 20, 5, 15, 30, 35, 5, 20, 0],
    'Family': [5, 0, 0, 0, 0, 35, 0, 5, 15, 0, 10, 20],
    'Horror': [10, 0, 5, 20, 20, 35, 25, 10, 5, 0, 10, 10]
}

df = pd.DataFrame(data)

# Set 'Movie No.' column as the index
df.set_index('Movie No.', inplace=True)

# Calculate percentage values for each genre within each movie
total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Create a stacked bar chart
plt.figure(figsize=(10, 6))
sns.set(style="white")  # Turn off background grid

# Use Seaborn's barplot function with stacked=True
ax = df_percentage.plot(kind='bar', stacked=True, cmap='viridis')

# Set the title and labels
plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Movies')
plt.ylabel('Percentage')

# Customize legend
handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5', 'Movie 6', 'Movie 7', 'Movie 8', 'Movie 9', 'Movie 10', 'Movie 11', 'Movie 12'],
    'Action': [5, 30, 30, 30, 20, 0, 35, 20, 5, 50, 45, 10],
    'Adventure': [0, 40, 20, 30, 20, 25, 25, 30, 30, 35, 15, 40],
    'Romance': [50, 10, 15, 0, 20, 0, 0, 5, 10, 10, 0, 20],
    'Fantasy': [30, 20, 30, 20, 20, 5, 15, 30, 35, 5, 20, 0],
    'Family': [5, 0, 0, 0, 0, 35, 0, 5, 15, 0, 10, 20],
    'Horror': [10, 0, 5, 20, 20, 35, 25, 10, 5, 0, 10, 10]
}

df = pd.DataFrame(data)

# Set 'Movie No.' column as the index
df.set_index('Movie No.', inplace=True)

# Calculate percentage values for each genre within each movie
total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Create a horizontal stacked bar chart
plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")

# Use Seaborn's barplot function with stacked=True
ax = df_percentage.plot(kind='barh', stacked=True, cmap='viridis')

# Set the title and labels
plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Percentage')
plt.ylabel('Movies')

# Customize legend
handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5', 'Movie 6', 'Movie 7', 'Movie 8', 'Movie 9', 'Movie 10', 'Movie 11', 'Movie 12'],
    'Action': [5, 30, 30, 30, 20, 0, 35, 20, 5, 50, 45, 10],
    'Adventure': [5, 40, 20, 30, 20, 25, 25, 30, 30, 35, 15, 40],
    'Romance': [45, 10, 15, 0, 20, 0, 0, 5, 10, 10, 0, 20],
    'Fantasy': [30, 20, 30, 20, 20, 5, 15, 30, 35, 5, 20, 0],
    'Family': [5, 0, 0, 0, 0, 35, 0, 5, 15, 0, 10, 20],
    'Horror': [10, 0, 5, 20, 20, 35, 25, 10, 5, 0, 10, 10]
}

df = pd.DataFrame(data)

# Set 'Movie No.' column as the index
df.set_index('Movie No.', inplace=True)

# Calculate percentage values for each genre within each movie
total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Create a horizontal stacked bar chart
plt.figure(figsize=(10, 6))
sns.set(style="white")

# Use Seaborn's barplot function with stacked=True
ax = df_percentage.plot(kind='barh', stacked=True, cmap='viridis')

# Set the title and labels
plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Percentage')
plt.ylabel('Movies')

# Remove the top and right spines (axes lines)
sns.despine()

# Customize legend
handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 12', 'Movie 11', 'Movie 10', 'Movie 9', 'Movie 8', 'Movie 7', 'Movie 6', 'Movie 5', 'Movie 4', 'Movie 3', 'Movie 2', 'Movie 1'],
    'Action': [10, 45, 50, 5, 20, 35, 0, 20, 30, 30, 30, 5],
    'Adventure': [40, 15, 35, 30, 30, 25, 25, 20, 30, 20, 40, 0],
    'Romance': [20, 0, 10, 10, 5, 0, 0, 20, 0, 15, 10, 50],
    'Fantasy': [0, 20, 5, 35, 30, 15, 5, 20, 20, 30, 20, 30],
    'Family': [20, 10, 0, 15, 5, 0, 35, 0, 0, 0, 0, 5],
    'Horror': [10, 10, 0, 5, 10, 25, 35, 20, 20, 5, 0, 10]
}

df = pd.DataFrame(data)

# Set 'Movie No.' column as the index
df.set_index('Movie No.', inplace=True)

# Calculate percentage values for each genre within each movie
total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Create a horizontal stacked bar chart
plt.figure(figsize=(10, 6))
sns.set(style="white")

# Use Seaborn's barplot function with stacked=True
ax = df_percentage.plot(kind='barh', stacked=True, cmap='viridis')

# Set the title and labels
plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Percentage')
plt.ylabel('Movies')

# Remove the top and right spines (axes lines)
sns.despine()

# Customize legend
handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame with the provided data
data = {
    'Movie No.': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5', 'Movie 6', 'Movie 7', 'Movie 8', 'Movie 9', 'Movie 10', 'Movie 11', 'Movie 12'],
    'Action': [5, 30, 30, 30, 20, 0, 35, 20, 5, 50, 45, 10],
    'Adventure': [5, 40, 20, 30, 20, 25, 25, 30, 30, 35, 15, 40],
    'Romance': [45, 10, 15, 0, 20, 0, 0, 5, 10, 10, 0, 20],
    'Fantasy': [30, 20, 30, 20, 20, 5, 15, 30, 35, 5, 20, 0],
    'Family': [5, 0, 0, 0, 0, 35, 0, 5, 15, 0, 10, 20],
    'Horror': [10, 0, 5, 20, 20, 35, 25, 10, 5, 0, 10, 10]
}

df = pd.DataFrame(data)
df.set_index('Movie No.', inplace=True)

total_per_movie = df.sum(axis=1)
df_percentage = df.div(total_per_movie, axis=0) * 100

# Define custom colors for each genre
genre_colors = ['red', 'brown', 'pink', 'green', 'blue', 'black']

# Create a horizontal stacked bar chart
plt.figure(figsize=(10, 6))
sns.set(style="white")

# Set the custom color palette
sns.set_palette(sns.color_palette(genre_colors))

ax = df_percentage.plot(kind='barh', stacked=True)

plt.title('Stacked Bar Chart of Movie Genres')
plt.xlabel('Percentage')
plt.ylabel('Movies')

sns.despine()

handles, labels = ax.get_legend_handles_labels()
ax.legend(reversed(handles), reversed(labels), loc='center right', bbox_to_anchor=(1.25, 0.5))

plt.show()