# -*- coding: utf-8 -*-
"""Movies Genre Line Bar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkdA8XlmN2qRAM6Af2x3iNeYKTN1aQXt
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Data
movies = list(range(1, 26))
genres = ['Action', 'Adventure', 'Romance', 'Fantasy', 'Family', 'Horror']
values = [
    [15, 25, 5, 50, 5, 0],
    [35, 15, 5, 45, 0, 0],
    [15, 30, 10, 45, 0, 0],
    [5, 0, 50, 30, 5, 10],
    [0, 30, 15, 25, 0, 30],
    [30, 40, 10, 20, 0, 0],
    [30, 20, 15, 30, 0, 5],
    [0, 30, 20, 20, 0, 30],
    [0, 0, 30, 20, 10, 40],
    [30, 30, 0, 20, 0, 20],
    [20, 20, 20, 20, 0, 20],
    [0, 10, 5, 40, 35, 10],
    [0, 0, 40, 20, 40, 0],
    [0, 25, 0, 5, 35, 35],
    [0, 30, 0, 25, 35, 10],
    [35, 25, 0, 15, 0, 25],
    [20, 30, 5, 30, 5, 10],
    [5, 10, 25, 35, 25, 0],
    [5, 30, 10, 35, 15, 5],
    [50, 40, 5, 5, 0, 0],
    [50, 35, 10, 5, 0, 0],
    [25, 25, 0, 25, 25, 0],
    [45, 15, 0, 20, 10, 10],
    [50, 15, 5, 30, 0, 0],
    [10, 40, 20, 0, 20, 10]
]

# Create a DataFrame
df = pd.DataFrame(values, columns=genres)

# Set the movie numbers as the index
df.index = movies

# Create stacked horizontal bar charts for each range
ranges = [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25)]
for start, end in ranges:
    subset = df.iloc[start - 1:end]
    sns.set(style="whitegrid")
    plt.figure(figsize=(10, 6))
    sns.barplot(data=subset, orient="h")
    plt.xlabel('Percentage')
    plt.ylabel('Movie No.')
    plt.title(f'Movie Genre Distribution (Movies {start} to {end})')
    plt.legend(loc='upper right', bbox_to_anchor=(1.4, 1.0))
    plt.tight_layout()

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Data
movies = list(range(1, 26))
genres = ['Action', 'Adventure', 'Romance', 'Fantasy', 'Family', 'Horror']
values = [
    [15, 25, 5, 50, 5, 0],
    [35, 15, 5, 45, 0, 0],
    [15, 30, 10, 45, 0, 0],
    [5, 0, 50, 30, 5, 10],
    [0, 30, 15, 25, 0, 30],
    [30, 40, 10, 20, 0, 0],
    [30, 20, 15, 30, 0, 5],
    [0, 30, 20, 20, 0, 30],
    [0, 0, 30, 20, 10, 40],
    [30, 30, 0, 20, 0, 20],
    [20, 20, 20, 20, 0, 20],
    [0, 10, 5, 40, 35, 10],
    [0, 0, 40, 20, 40, 0],
    [0, 25, 0, 5, 35, 35],
    [0, 30, 0, 25, 35, 10],
    [35, 25, 0, 15, 0, 25],
    [20, 30, 5, 30, 5, 10],
    [5, 10, 25, 35, 25, 0],
    [5, 30, 10, 35, 15, 5],
    [50, 40, 5, 5, 0, 0],
    [50, 35, 10, 5, 0, 0],
    [25, 25, 0, 25, 25, 0],
    [45, 15, 0, 20, 10, 10],
    [50, 15, 5, 30, 0, 0],
    [10, 40, 20, 0, 20, 10]
]

# Create a DataFrame
df = pd.DataFrame(values, columns=genres)

# Set the movie numbers as the index
df.index = movies

# Create stacked horizontal bar charts for each range
ranges = [(1, 5), (6, 10), (11, 15), (16, 20), (21, 25)]

sns.set(style="whitegrid")

for start, end in ranges:
    subset = df.iloc[start - 1:end]
    plt.figure(figsize=(10, 6))
    subset.plot(kind='barh', stacked=True)
    plt.xlabel('Percentage')
    plt.ylabel('Movie No.')
    plt.title(f'Movie Genre Distribution (Movies {start} to {end})')
    plt.legend(loc='upper right', bbox_to_anchor=(1.4, 1.0))
    plt.tight_layout()

plt.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Data
timestamps = ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80']
genres = ['Action', 'Adventure', 'Romance', 'Fantasy', 'Family', 'Horror']

data = [
    [0, 0, 0, 0, 0, 0],
    [0, 0, 60, 20, 10, 0],
    [0, 0, 30, 20, 10, 30],
    [0, 0, 10, 20, 10, 30],
    [0, 0, 40, 10, 10, 0],
    [0, 0, 40, 10, 10, 0],
    [0, 0, 30, 10, 10, 0],
    [30, 0, 30, 10, 10, 20]
]

# Create a subplot grid
rows = len(genres)
cols = 1
fig = make_subplots(rows=rows, cols=cols, shared_xaxes=True, vertical_spacing=0.05,
                    subplot_titles=genres, x_title='Timestamp', y_title='Percentage')

# Create line charts for each genre
for i, genre in enumerate(genres):
    genre_data = [row[i] for row in data]
    fig.add_trace(go.Scatter(x=timestamps, y=genre_data, mode='lines+markers', name=genre), row=i+1, col=1)

# Update layout
fig.update_layout(title='Sequence-Based Design - Genre Distribution Over Time', showlegend=False)

# Show the plot
fig.show()

!pip install altair vega_datasets

import altair as alt
import pandas as pd

# Data
data = {
    'Movie No.': [1, 2, 3, 4, 5],
    'Action': [15, 35, 15, 5, 0],
    'Adventure': [25, 15, 30, 0, 30],
    'Romance': [5, 5, 10, 50, 15],
    'Fantasy': [50, 45, 45, 30, 25],
    'Family': [5, 0, 0, 5, 0],
    'Horror': [0, 0, 0, 10, 30]
}

df = pd.DataFrame(data)

# Convert data to long format
df_long = df.melt('Movie No.', var_name='Genre', value_name='Percentage')

# Create a stacked horizontal bar chart using Altair
chart = alt.Chart(df_long).mark_bar().encode(
    x=alt.X('Percentage:Q', stack='normalize', axis=alt.Axis(format='%')),
    y=alt.Y('Movie No.:O'),
    color=alt.Color('Genre:N', scale=alt.Scale(scheme='category20b')),
    order=alt.Order('Genre:N')
).properties(
    title='Stacked Horizontal Bar Chart - Movie Genre Distribution'
)

# Display the chart using Jupyter Notebook's display() function
chart

import csv

matrix = [
    [38, 19, 17, 11, 5, 10],
    [5, 16, 7, 12, 10, 50],
    [1, 1, 22, 17, 59, 0],
    [22, 26, 9, 8, 21, 14],
    [3, 39, 3, 26, 12, 17],
    [14, 13, 21, 15, 18, 19],
    [10, 23, 6, 33, 8, 20],
    [26, 5, 14, 15, 23, 17],
    [21, 24, 16, 3, 31, 5],
    [23, 5, 9, 26, 12, 25],
    [16, 12, 2, 16, 44, 10],
    [18, 12, 24, 7, 8, 31],
    [25, 4, 25, 16, 10, 20]
]

with open('matrix.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(matrix)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data (same as before)
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set a custom color palette
palette = sns.color_palette("Set2")

# Set the style of seaborn and adjust the context
sns.set(style="whitegrid", context="talk")

# Create a stacked line chart with improved aesthetics
plt.figure(figsize=(10, 6))
sns.lineplot(data=df.drop('Timestemp', axis=1), palette=palette, linewidth=2, marker='o')

plt.title('Stacked Line Chart - Genre Distribution Over Time')
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.legend(title='Genre')

# Tighten the layout and remove top and right spines
sns.despine()
plt.tight_layout()

# Show the plot
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Line plot with markers
plt.figure(figsize=(10, 6))
sns.lineplot(x='Timestemp', y='Action', data=df, marker='o', label='Action')
sns.lineplot(x='Timestemp', y='Adventure', data=df, marker='o', label='Adventure')
sns.lineplot(x='Timestemp', y='Romance', data=df, marker='o', label='Romance')
sns.lineplot(x='Timestemp', y='Fantasy', data=df, marker='o', label='Fantasy')
sns.lineplot(x='Timestemp', y='Family', data=df, marker='o', label='Family')
sns.lineplot(x='Timestemp', y='Horror', data=df, marker='o', label='Horror')

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Line Chart with Markers - Genre Counts Over Time')
plt.legend()
plt.tight_layout()

plt.show()

# Line plot without markers
plt.figure(figsize=(10, 6))
sns.lineplot(x='Timestemp', y='Action', data=df, label='Action')
sns.lineplot(x='Timestemp', y='Adventure', data=df, label='Adventure')
sns.lineplot(x='Timestemp', y='Romance', data=df, label='Romance')
sns.lineplot(x='Timestemp', y='Fantasy', data=df, label='Fantasy')
sns.lineplot(x='Timestemp', y='Family', data=df, label='Family')
sns.lineplot(x='Timestemp', y='Horror', data=df, label='Horror')

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Line Chart without Markers - Genre Counts Over Time')
plt.legend()
plt.tight_layout()

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(10, 6))
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', marker='o')

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart - Genre Counts Over Time')
plt.legend(title='Genre')
plt.tight_layout()

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(8, 4))  # Adjust the figure size
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', marker='o', palette='tab20')

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart - Genre Counts Over Time')
plt.legend(title='Genre')
plt.tight_layout()

# Remove background grid lines
plt.grid(False)

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(8, 4))  # Adjust the figure size

# Stacked area chart
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', marker='o', palette='tab20')

# Bar chart for "Romance" inside the stacked area chart
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color='orange', alpha=0.7)

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart with Romance Bar - Genre Counts Over Time')
plt.legend().remove()  # Remove the legend

# Remove background grid lines
plt.grid(False)

plt.show()



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(10, 6))  # Adjust the figure size

# Stacked area chart
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', palette='tab20')

# Bar chart for "Romance" inside the stacked area chart
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color='salmon', alpha=0.7)

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart with Romance Bar - Genre Counts Over Time')

# Adding the legend back
plt.legend(title='Genre')

# Remove background grid lines
plt.grid(False)

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(10, 6))  # Adjust the figure size

# Stacked area chart
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', palette='tab20')

# Bar chart for "Romance" inside the stacked area chart
romance_color = sns.color_palette("tab20")[2]  # Get the color for Romance
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=romance_color, alpha=0.7)

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart with Romance Bar - Genre Counts Over Time')

# Adding the legend back
plt.legend(title='Genre')

# Remove background grid lines
plt.grid(False)

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(10, 6))  # Adjust the figure size

# Stacked area chart with markers
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', palette='tab20', marker='o')

# Bar chart for "Romance" inside the stacked area chart
romance_color = sns.color_palette("pastel")[2]  # Get a different color for Romance
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=romance_color, alpha=0.7)

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart with Romance Bar - Genre Counts Over Time')

# Adding the legend back
plt.legend(title='Genre')

# Remove background grid lines
plt.grid(False)

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(10, 6))  # Adjust the figure size

# Stacked area chart with markers
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', palette='tab20', marker='o', linewidth=2.5)

# Bar chart for "Romance" inside the stacked area chart
romance_color = sns.color_palette("pastel")[2]  # Get a different color for Romance
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=romance_color, alpha=0.7, zorder=10)

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart with Romance Bar - Genre Counts Over Time')

# Adding the legend back
plt.legend(title='Genre')

# Remove background grid lines
plt.grid(False)

# Adjust the spacing between the line graph and bar graph
plt.subplots_adjust(bottom=0.15)

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(10, 6))  # Adjust the figure size

# Stacked area chart with markers
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', palette='tab20', marker='o', linewidth=2.5)

# Bar chart for "Romance" with matching color
romance_color = sns.color_palette("tab20")[2]  # Get the Romance line color
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=romance_color, alpha=0.7, zorder=10)

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Bar Chart for Romance and Stacked Area Chart - Genre Counts Over Time')

# Adding the legend back
plt.legend(title='Genre')

# Remove background grid lines
plt.grid(False)

# Adjust the spacing between the plots
plt.subplots_adjust(top=0.75, bottom=0.25)

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Specify different color palettes for the lines and bars
line_palettes = ['husl', 'tab20', 'Set1', 'Dark2']
bar_palettes = ['tab20', 'husl', 'Dark2', 'Set1']

for i in range(4):
    plt.figure(figsize=(10, 6))  # Adjust the figure size

    # Choose color palettes for lines and bars
    line_colors = sns.color_palette(line_palettes[i], n_colors=6)
    bar_colors = sns.color_palette(bar_palettes[i])[2]

    # Stacked area chart with markers and specified colors
    sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', palette=line_colors, marker='o', linewidth=2.5)

    # Bar chart for "Romance" with matching color
    sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=bar_colors, alpha=0.7, zorder=10)

    plt.xticks(rotation=45)
    plt.xlabel('Timestemp')
    plt.ylabel('Count')
    plt.title(f'Color Combination {i+1}: Romance Stacked Area and Bar Chart')

    # Adding the legend back
    plt.legend(title='Genre')

    # Remove background grid lines
    plt.grid(False)

    # Adjust the spacing between the plots
    plt.subplots_adjust(top=0.75, bottom=0.25)

    plt.tight_layout()
    plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a stacked area chart using Seaborn
plt.figure(figsize=(10, 6))  # Adjust the figure size

# Stacked area chart with markers
sns.lineplot(x='Timestemp', y='Count', data=df_long, hue='Genre', palette='tab20', marker='o', linewidth=2.5)

# Bar chart for "Romance"
romance_color = sns.color_palette("tab20")[2]  # Get a different color for Romance
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=romance_color, alpha=0.7, zorder=10)

plt.xticks(rotation=45)
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.title('Stacked Area Chart with Romance Bar - Genre Counts Over Time')

# Adding the legend back
plt.legend(title='Genre')

# Remove background grid lines
plt.grid(False)

# Adjust the spacing between the plots
plt.subplots_adjust(top=0.75, bottom=0.25)

plt.tight_layout()
plt.show()



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a figure with subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 12), sharex=True)

# Bar chart for "Romance"
romance_color = sns.color_palette("tab20")[2]  # Get a different color for Romance
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=romance_color, alpha=0.7, ax=ax1)
ax1.set_ylabel('Count')
ax1.set_title('Bar Chart for Romance')

# Stacked area chart with markers
sns.lineplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] != 'Romance'], hue='Genre', palette='tab20', marker='o', linewidth=2.5, ax=ax2)
ax2.set_ylabel('Count')
ax2.set_title('Stacked Area Chart - Genre Counts Over Time')

plt.xticks(rotation=45)
plt.xlabel('Timestemp')

# Adding the legend back
ax2.legend(title='Genre')

# Remove background grid lines
ax1.grid(False)
ax2.grid(False)

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Melt the data to long format
df_long = pd.melt(df, id_vars=['Timestemp'], var_name='Genre', value_name='Count')

# Create a figure with subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 12), sharex=True)

# Stacked area chart with markers
sns.lineplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] != 'Romance'], hue='Genre', palette='tab20', marker='o', linewidth=2.5, ax=ax1)
ax1.set_ylim(0, 100)  # Set y-axis range
ax1.set_ylabel('Count')
ax1.set_title('Stacked Area Chart - Genre Counts Over Time')

# Bar chart for "Romance"
romance_color = sns.color_palette("tab20")[2]  # Get a different color for Romance
sns.barplot(x='Timestemp', y='Count', data=df_long[df_long['Genre'] == 'Romance'], color=romance_color, alpha=0.7, ax=ax2)
ax2.set_ylim(0, 100)  # Set y-axis range
ax2.set_ylabel('Count')
ax2.set_title('Bar Chart for Romance')

plt.xticks(rotation=45)
plt.xlabel('Timestemp')

# Adding the legend back
ax1.legend(title='Genre')

# Remove background grid lines
ax1.grid(False)
ax2.grid(False)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data
data = {
    'Timestemp': ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100', '101-120', '121-130', '131-140'],
    'Action': [38, 5, 1, 22, 3, 14, 10, 26, 21, 23, 16, 18, 25],
    'Adventure': [19, 16, 1, 26, 39, 13, 23, 5, 24, 5, 12, 12, 4],
    'Romance': [17, 7, 22, 9, 3, 21, 6, 14, 16, 9, 2, 24, 25],
    'Fantasy': [11, 12, 17, 8, 26, 15, 33, 15, 3, 26, 16, 7, 16],
    'Family': [5, 10, 59, 21, 12, 18, 8, 23, 31, 12, 44, 8, 10],
    'Horror': [10, 50, 0, 14, 17, 19, 20, 17, 5, 25, 10, 31, 20]
}

df = pd.DataFrame(data)

# Set the style
sns.set(style="whitegrid")

# Line Graph for All Genres
plt.figure(figsize=(10, 6))
for genre in ['Action', 'Adventure', 'Romance', 'Fantasy', 'Family', 'Horror']:
    plt.plot(df['Timestemp'], df[genre], marker='o', label=genre)

plt.title('Genre Counts Over Time')
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.grid(False)
# Bar Chart for Romance Genre
romance_color = sns.color_palette("tab10")[2]  # Get a different color for Romance
plt.figure(figsize=(10, 4))
sns.barplot(x='Timestemp', y='Romance', data=df, color=romance_color, alpha=0.7)
plt.title('Bar Chart for Romance Genre')
plt.xlabel('Timestemp')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.grid(False)

plt.show()

